<a href="https://colab.research.google.com/github/Ahmethan96/AWS/blob/main/Ahmethan96/Data_science/tree/main/Pytorch/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Creating tensors**

In [2]:
import torch

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
print(type(scalar))

<class 'torch.Tensor'>


In [7]:
scalar.ndim

0

In [8]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [9]:
print(type(scalar.item()))

<class 'int'>


In [10]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [14]:
vector.shape
# The above returns torch.Size([2]) which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).

torch.Size([2])

In [15]:
# Matrix
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [19]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],[4, 5, 6],[7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [23]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size= (3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.1097, 0.4055, 0.2340, 0.3306],
         [0.8142, 0.1906, 0.8313, 0.0181],
         [0.9818, 0.8682, 0.5116, 0.7536]]),
 torch.float32)